# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-12 10:15
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    EmailMarketingCampaign = apps.get_model("django_constant_contact",
                                            "EmailMarketingCampaign")
    db_alias = schema_editor.connection.alias
    for campaign in EmailMarketingCampaign.objects.all():
        campaign.data_new = campaign.data
        campaign.save()


def reverse(apps, schema_editor):
    EmailMarketingCampaign = apps.get_model("django_constant_contact",
                                            "EmailMarketingCampaign")
    db_alias = schema_editor.connection.alias
    for campaign in EmailMarketingCampaign.objects.all():
        campaign.data_new = ""
        campaign.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_constant_contact', '0002_emailmarketingcampaign_new_data'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse)
    ]
