# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-12 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_constant_contact', '0003_auto_20180912_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmarketingcampaign',
            name='data',
        ),
    ]
